"""make_brand_id_nullable

Revision ID: db6006ec09bd
Revises: a65fa1e49e33
Create Date: 2026-08-01 10:34:25.220439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6006ec09bd'
down_revision: Union[str, Sequence[str], None] = 'a65fa1e49e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
